/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package practica_segundaIdea.carreras_gui;

import java.util.Collection;
import java.util.Collections;
import practica_segundaIdea.dto.Carrera;
import practica_segundaIdea.dto.Participante;

/**
 *
 * @author USER
 */
public class InformeCarrera extends javax.swing.JDialog {

    Carrera carrera;
    
    /** Creates new form InformeCarrera */
    public InformeCarrera(java.awt.Frame parent, boolean modal,Carrera carrera) {
        super(parent, modal);
        initComponents();
        this.carrera=carrera;
        escribe();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(4);
        jTextArea1.setRows(30);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 public void escribe(){
     int cont=0;
     jTextArea1.append("Carrera:  "+carrera.getNomCarrera()+"\n");
     jTextArea1.append("Fecha:    "+carrera.getFecha()+"\n\n");
     for(Participante p: carrera.getListaDeParticipantes()){
         cont++;
         jTextArea1.append("Nº"+cont+":  "+p.getDorsal()+"      "+p.getTiempo()+"      "+p.getNombre()+"\n");
     }
     
 }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables

}
